### ISSUE TITLE
Bug na mensagem de finalização

### ISSUE THREAD

**Issue by ictecnologiaoficial** [ldurans/izing.open.io#103]
Estou recebendo reabertura de chamado quando clicamos em resolver na conversa, e ai reabre novamente. como resolver.

**Comment by paulinhovba** [comment]
Estou recebendo reabertura de chamado quando clicamos em resolver na conversa, e ai reabre novamente. como resolver. 
Eu também!

**Comment by jorgecosta138** [comment]
Resolvi esse problema não colocando nenhuma variável na mensagem de despedida.
