### ISSUE TITLE
Erro na Instalação via Docker Compose

### ISSUE THREAD

**Issue by Natan738** [ldurans/izing.open.io#104]
está dando um problema quando estou instalando o izing via docker.
![image](https://user-images.githubusercontent.com/119529533/211170331-98e7597a-26b7-4f9b-9797-9ea7af8d3f19.png)
analisando os container vi que tem um que não está iniciando.
![image](https://user-images.githubusercontent.com/119529533/211170456-b42772fa-e473-4d7c-a03a-4b25669c5dce.png)
gostaria de saber como posso está fazendo para resolver esse problema?

**Comment by andrerds** [comment]
Mesmo b.o aqui, não sei o que pode ser , alguém consegui ter alguma ideia do que pode ser, eu deixei as configurações padrão do .env!

**Comment by zhiru** [comment]
esse container pelo que eu saiba é só um patch para correção do postgres ele não fica ativo mesmo.

**Comment by sirkobr4** [comment]
> está dando um problema quando estou instalando o izing via docker. ![image](https://user-images.githubusercontent.com/119529533/211170331-98e7597a-26b7-4f9b-9797-9ea7af8d3f19.png) analisando os container vi que tem um que não está iniciando. ![image](https://user-images.githubusercontent.com/119529533/211170456-b42772fa-e473-4d7c-a03a-4b25669c5dce.png) gostaria de saber como posso está fazendo para resolver esse problema?

Tive o mesmo problema, o problema é que o sequelize nao está global no NPM desse container.
Só rodar esse comando 

docker compose exec -it izing-backend bash -c 'npm install -g sequelize-cli'

E depois rodar o outro comando qeu tem em seguida.

**Comment by williamcostaramos** [comment]
O container que nao started não impede o Izing de funcionar.
