### ISSUE TITLE
Webhook para enviar mensagens recebidas para ferramenta externa

### ISSUE THREAD

**Issue by julioagostini** [ldurans/izing.open.io#105]
Oi Ldurans e equipe, parabéns pelo ótimo trabalho, impressionante o que fizeram.
Gostei muito da API multitenant, isso nos proporciona termos varios clientes na mesma instalação.
Estou tentando implementar um chatbot com consulta a dados em banco de dados através do n8n (uma ferramenta maravilhosa também, podendo integrar fluxos com bancos, planilhas do google ...) porém não consigo configurar um webhook para enviar as mensagens para uma ferramenta externa, encontrei apenas webhook para os status das mensagens.
Se conseguíssemos juntar izing com n8n as possibilidades de integrações com soluções externas seriam ilimitadas.

**Comment by rodrigofsantos** [comment]
amigo conseguiu algo ?
