### ISSUE TITLE
Error de Inicio de WhatsApp

### ISSUE THREAD

**Issue by Args2014** [ldurans/izing.open.io#107]
La leer el código QR no inicia el WhatsApp  
![image](https://user-images.githubusercontent.com/123979091/215653967-7270602e-e686-478e-bf34-2a0f2baaf739.png)

**Comment by thaylan77** [comment]
ei boludo resolveste?

**Comment by JrZavaschi** [comment]
run in backend:
npm i whatsapp-web.js --save
npm restart all

and retry.
