### ISSUE TITLE
Erro no bot ao encaminhar mensagem de qualquer resposta

### ISSUE THREAD

**Issue by raphapopi** [ldurans/izing.open.io#108]
Ao tentar encaminhar um usuário para próxima etapa do bot utilizando a condição "Se qualquer resposta" o bot não manda para próxima etapa. Só funciona se definir uma resposta em específico. Como resolver ?

Print: https://prnt.sc/QqHlmO6iOFoB

**Comment by PauloBettin** [comment]
Meu está assim também não obedece parâmetro de qualquer resposta conseguiu resolver?
