### ISSUE TITLE
HELP, instalacao via docker backend crash

### ISSUE THREAD

**Issue by codsec** [ldurans/izing.open.io#111]
![image](https://user-images.githubusercontent.com/44205014/218613757-16e4a336-d851-4329-8361-347dbe54fb8c.png)

tudo aparentemente funciona porem quando eu dou npm start no backend ele simplesmente crasha depois de 10segundos...

Meus passos:

`docker run --name postgresql -e POSTGRES_USER=izing -e POSTGRES_PASSWORD=password -p 5432:5432 -v /data:/var/lib/postgresql/data3 -d postgres`

`docker run -e TZ="America/Sao_Paulo" --name redis-izing -p 6379:6379 -d --restart=always redis:latest redis-server --appendonly yes --requirepass "password"`

`docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 --restart=always --hostname rabbitmq -v /data:/var/lib/rabbitmq rabbitmq:3-management-alpine`

cd izing/backend
npm install --force
npm run build
npm run db:migrate
npx sequelize db:seed:all

cd izing/frontend
npm install
npm i -g @quasar/cli
npx quasar build -P -m pwa
npx quasar dev

backend .env
![image](https://user-images.githubusercontent.com/44205014/218618970-881820e3-391d-4475-91a6-04c5d65d4947.png)
frontend .env
![image](https://user-images.githubusercontent.com/44205014/218618988-aedb434c-e710-4fa1-9ed7-aecd4504ca5c.png)

frontend funciona belezinha, mas o backend simplesmente crasha sem exibir nenhum erro...

**Comment by JrZavaschi** [comment]
Host do banco de dados e redis, utilizar localhost ou 127.0.0.1

**Comment by codsec** [comment]
> Host do banco de dados e redis, utilizar localhost ou 127.0.0.1

Aparentemente funcionou, porem agora apresenta um novo erro/crash;

![image](https://user-images.githubusercontent.com/44205014/218620005-bf739f2c-dc8f-4f9e-ad4a-ee78a35f4c54.png)

**Comment by codsec** [comment]
@JrZavaschi @ldurans Sabe de alguma coisa que possa ser?

**Comment by JrZavaschi** [comment]
Confere a porta no .env do seu frontend, está apontando para 3100 mas seu backend está rodando na porta 3000.
No .env do backend, muda a porta do proxy para a mesma do backend para execução local.

**Comment by codsec** [comment]
> Confere a porta no .env do seu frontend, está apontando para 3100 mas seu backend está rodando na porta 3000. No .env do backend, muda a porta do proxy para a mesma do backend para execução local.

Vlw agora no localhost tudo funciona perfeitamente, porem agora fui tentar colocar meus subdominios e não funciona, saberia me informar oq estou fazendo de errado... @JrZavaschi 

.env backend
![image](https://user-images.githubusercontent.com/44205014/218815695-b3f23999-96ae-4a54-8567-a8fd26b17a4a.png)
![image](https://user-images.githubusercontent.com/44205014/218815858-d3b71cb4-a3ff-4529-b706-176487fa3f4c.png)

.env frontend
![image](https://user-images.githubusercontent.com/44205014/218815948-c76dd2d9-227d-4f1e-9587-7716fa3911dd.png)

**Comment by codsec** [comment]
Outra coisa que está ocorrendo é que quando eu tento scanear o codigo QR ele não funciona e apresenta esse erro no console do backend...

![image](https://user-images.githubusercontent.com/44205014/218819749-3cf967ec-a412-4c25-a016-b7d02670231e.png)
