### ISSUE TITLE
Sequelize command not found

### ISSUE THREAD

**Issue by sirkobr4** [ldurans/izing.open.io#112]
Boa tarde prezados,

Ja tentei de tudo mas não consigo fazer funcionar o docker do projeto...
Já tentei instalar manualmente no terminal que ta rodando o backend mas não consigo parar com esse erro:
![image](https://user-images.githubusercontent.com/125281882/218839724-33b854ca-7393-4e49-92c7-f72d8747a5b9.png)

Procedimentos que fiz para tentar simular mais facil:

Clono o repositorio > Retiro os .example dos arquivos .env e rodo o comando:
 "docker compose -f "docker-compose.yml" up  --build" ##Sem o -d para poder ver o que está acontecendo.

E então o izing-backend fica reiniciando sem parar dando essa mensagem de erro.

Desde já,
Agradeço.

**Comment by marlonwanger** [comment]
O mesmo aconteceu aqui, editei a img fazendo um install no sequelize-cli -g para ver o que acontecia agora o error mudou para 
" Unable to resolve sequelize package in /usr/src/app"

**Comment by williamcostaramos** [comment]
O sequelize funciona smente após executar o build dos arquivos .ts
Na pasta onde está o backend execute:

npm install
npm run build
npx sequelize db:migrate
npx sequelize db:seed:all

**Comment by davioliveeira** [comment]
@williamcostaramos quando devo rodar esses comandos? depois de rodar os comandos do docker?

**Comment by williamcostaramos** [comment]
@davioliveeira apos subir o container de banco de dados voce pode rodar os comandos na pasta backend.
`npm install
npm run build
npx sequelize db:migrate
npx sequelize db:seed:all`

Se sua conexao com o banco foi configurada corretamente tudo vai funcionar.
caso de algum erro no sequelize provavelmente voce deve copilar o projeto para que os comando do sequelize seja executados
