### ISSUE TITLE
nao atualiza conforme recebe e envia mensagem

### ISSUE THREAD

**Issue by Jeferson-Diniz** [ldurans/izing.open.io#113]
ao fazer scan do qrcode, o whatsapp conecta mas nao mostra conectado, só se recarregar a página, a mesma coisa acontece quando envia e recebe mensagem, eu estou configurando algo errado ou é o próprio sistema com erro?

**Comment by NoNAT-Telecom** [comment]
@Jeferson-Diniz vc conseguiu resolver esse problema?

**Comment by tetestylus** [comment]
Como resolveu?
