### ISSUE TITLE
Erro no frontend após instalação

### ISSUE THREAD

**Issue by rogeriosims** [ldurans/izing.open.io#114]
Apos concluir a instalação, e fazer o build do frontend, não consigo acessar o site, pois o navegador fica tentando carregar um arquivo js inexistente.

Conferi na pasta dist/pwa/js e não existe tal arquivo.

https://izing.tecnologiacorporativa.com.br/js/vendor.d73871f9.js

![image](https://user-images.githubusercontent.com/12436276/219088483-e939be99-0a9e-42a3-99a6-8d25ef727cd0.png)

Ao rodar o comando do quasar recebo o seguinte warning:

![image](https://user-images.githubusercontent.com/12436276/219094161-bd118df7-cbd2-4cd9-afb0-894248e0da8a.png)

Procurei pelo arquivo aqui no repo e tambem na internet e não achei nada.

Poderia verificar?

**Comment by williamcostaramos** [comment]
@rogeriosims tenta fazer o build novamente e limpa o cache do seu navegador
