### ISSUE TITLE
502 Bad Gateway Error on Backend

### ISSUE THREAD

**Issue by JvilleDev** [ldurans/izing.open.io#115]
Olá. Eu usei o instalador para isso, só não sei o que deu errado.

Quando eu abro o back-end, ele deve dizer "Cannot GET /", mas diz "Bad Gateway 502"
PS: Estou usando um tradutor, então não sei se está bem escrito

Nginx ERROR log:

> `2023/02/19 16:54:45 [error] 33976#33976: *258 connect() failed (111: Unknown error) while connecting to upstream, client: 190.71.82.210, server: api.mariovillegasnetworker.com, request: "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1", upstream: "http://127.0.0.1:3000/socket.io/?EIO=4&transport=websocket", host: "api.mariovillegasnetworker.com"
2023/02/19 16:54:50 [error] 33976#33976: *260 connect() failed (111: Unknown error) while connecting to upstream, client: 190.71.82.210, server: api.mariovillegasnetworker.com, request: "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1", upstream: "http://127.0.0.1:3000/socket.io/?EIO=4&transport=websocket", host: "api.mariovillegasnetworker.com"
2023/02/19 16:54:51 [error] 33976#33976: *262 connect() failed (111: Unknown error) while connecting to upstream, client: 190.71.82.210, server: api.mariovillegasnetworker.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "api.mariovillegasnetworker.com"
2023/02/19 16:54:51 [error] 33976#33976: *262 connect() failed (111: Unknown error) while connecting to upstream, client: 190.71.82.210, server: api.mariovillegasnetworker.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:3000/favicon.ico", host: "api.mariovillegasnetworker.com", referrer: "https://api.mariovillegasnetworker.com/"
2023/02/19 16:54:59 [error] 33976#33976: *266 connect() failed (111: Unknown error) while connecting to upstream, client: 39.110.218.101, server: api.mariovillegasnetworker.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "api.mariovillegasnetworker.com"
2023/02/19 16:55:23 [error] 33976#33976: *268 recv() failed (104: Unknown error) while reading response header from upstream, client: 54.242.203.59, server: api.mariovillegasnetworker.com, request: "GET /.git/config HTTP/1.1", upstream: "http://127.0.0.1:3000/.git/config", host: "api.mariovillegasnetworker.com"
2023/02/19 16:55:28 [error] 33976#33976: *270 connect() failed (111: Unknown error) while connecting to upstream, client: 39.110.218.101, server: api.mariovillegasnetworker.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "api.mariovillegasnetworker.com"
2023/02/19 16:55:33 [crit] 33976#33976: *324 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client: 174.138.95.152, server: 0.0.0.0:443
2023/02/19 16:56:36 [error] 33976#33976: *366 connect() failed (111: Unknown error) while connecting to upstream, client: 190.71.82.210, server: api.mariovillegasnetworker.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "api.mariovillegasnetworker.com"
2023/02/19 16:56:36 [error] 33976#33976: *366 connect() failed (111: Unknown error) while connecting to upstream, client: 190.71.82.210, server: api.mariovillegasnetworker.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:3000/favicon.ico", host: "api.mariovillegasnetworker.com", referrer: "https://api.mariovillegasnetworker.com/"`

**Comment by Jvillepb** [comment]
Nginx backend site-enabled conf:

> `  GNU nano 6.2                                                                                izing.io-backend                                                                                          
server {
  server_name api.mariovillegasnetworker.com;
  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_cache_bypass $http_upgrade;
  }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/api.mariovillegasnetworker.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.mariovillegasnetworker.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = api.mariovillegasnetworker.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
 server_name api.mariovillegasnetworker.com;
    listen 80;
    return 404; # managed by Certbot

}`
