### ISSUE TITLE
Variáveis no chatbot

### ISSUE THREAD

**Issue by NoNAT-Telecom** [ldurans/izing.open.io#116]
Pessoal alguém poderia listar as variáveis que existem já funcionando no chatbot.

E também se alguém tem o conhecimento de como poderíamos colocar mais variáveis dentro dos atendimentos.

**Comment by JoseMariani** [comment]
Yo te prodia ayudar con este modificcion, contactame y te puedo dar un precio para ayudarte, saludos.
