### ISSUE TITLE
Izing nao loga após a instalação

### ISSUE THREAD

**Issue by yurigoes** [ldurans/izing.open.io#117]
Izing nao ta logando, fiz a instalação toda certinha e nao funaiona.

**Comment by williamcostaramos** [comment]
pode enviar uma print da tela de login, de preferencia com o console do navegador aberto

**Comment by JoelAcosta1984** [comment]
Estou tendo um problema parecido com este toda a configuração toda correta , porem quando tenta abrir o link do frontend aparece esta tela
![image](https://user-images.githubusercontent.com/129418072/228901258-1b2a1da8-2167-4002-aae0-63a65002053c.png)

**Comment by JoelAcosta1984** [comment]
> Esse erro ocorre porque o Nginx está apontando para a pasta de instalação padrão.

Obrigado, agora foi, mesmo fazendo todas as configurações devidas colocando o user padrão, não loga

**Comment by williamcostaramos** [comment]
Testa a conexão com postgres pode ser que o backend não esteja conectando no banco de dados.

Olha o container do postgres está funcionando
