### ISSUE TITLE
Ajustar a taxa de UPLOAD para envio de medias.

### ISSUE THREAD

**Issue by taradodovaso** [ldurans/izing.open.io#119]
Atualmente o WhatsApp possibilita o envio de arquivos até 100 MB porém o Izing limita os arquivos acima de 10 MB, estou abrindo este tópico para ajudar designer que assim como eu precisam enviar constantemente arquivos mais pesados via WhatsApp. 

Agradeço muito quem puder colaborar com tópico. 🙏

**Comment by Disapper** [comment]
É possível aumentar esse upload acima de 10MB?
