### ISSUE TITLE
Se você vir esta página, o servidor web nginx foi instalado com sucesso e está funcionando. Configuração adicional é necessária

### ISSUE THREAD

**Issue by JoelAcosta1984** [ldurans/izing.open.io#122]
Estou com este problema sobre configuração adicional no NGINX conforme o print abaixo

![image](https://user-images.githubusercontent.com/129418072/228902509-03954e1a-e9e0-495e-a901-e55f72ec9144.png)

Como corrigir ou qual config necessária para poder finalizar esta etapa.

Alguém pode ajudar

**Comment by tomanyapi** [comment]
Qual é o seu problema amigo?

**Comment by JoelAcosta1984** [comment]
> > Qual é o seu problema amigo?
> 
> Opa, boa tarde, o problema inicial, consegui resolver após refazer o passo a passo, algumas vezes, agora estou tendo este tipo de problemas
> 
> ![image](https://user-images.githubusercontent.com/129418072/229582941-90450c51-68b8-4710-ac86-89d85b20c1a9.png)
> 
> ![image](https://user-images.githubusercontent.com/129418072/229582996-f5e6deaf-ae3b-4401-998a-1fa65eaa2e67.png)
> 
> na fase teste o cliente ou usuário de teste em questão, não visualiza as respostas e quando aparece outro ticket em aberto aparece erro de servidor, estou perdido nesse ponto

![image](https://user-images.githubusercontent.com/129418072/229585856-0423778b-c3bb-42ea-b002-571c26c45a39.png)


Acontecendo isso tambem
