### ISSUE TITLE
[ERRO] Izing parando de enviar mensagens. QUEM PODER AJUDAR DESDE JÁ AGRADEÇO!

### ISSUE THREAD

**Issue by arturneto01** [ldurans/izing.open.io#123]
estou tendo uns problemas no Izing. ele não chega a desconectar recebe mensagens, porem do nada ele para de mandar mensagens. daí tenho que atualizar o WhatsApp web.js toda vez. JÁ FIZ O PROCEDIMENTO ABAIXO, MAIS NADA RESOLVEL.

Removi a pasta node modules em /deployzdg/izing.io/backend, 

Em em /deployzdg/izing.io/backend, dei um npm install --force

Em /deployzdg/izing.io/backend, Atualizei a versão do whatsapp-web.js, e verifiquei no package.json se estava em 1.19.5

Em em /deployzdg, (sem ser no backend) somente em deployzdg dei o comando 
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install -y ./google-chrome-stable_current_amd64.deb

Depois fiz a build em em /deployzdg/izing.io/backend e dei um restart all

Percebi que após o procedimento apareceu 2 arquivos novos em: /deployzdg é normal? Segue o link
https://drive.google.com/file/d/1N01dnQOdupXk_m32c9Xtc4JqTK9WXiFm/view?usp=share_link

SE ALGUEM PODER ME AJUDAR DESDE JÁ AGRADESÇO...!

**Comment by fotaviog** [comment]
Boa tarde Artur.

Estou com o mesmo problema. 

Já tentei todas as dicas que achei, nenhuma deu certo. 

Neste comentário (https://github.com/ldurans/izing.open.io/issues/93) o @marcosambrozio diz claramente que foi depois que atualizou da 1.6 para 1.9.

No histórico de versões (na 1.7) menciona a seguinte "correção"(https://github.com/ldurans/izing.open.io/releases):
_ajuste no scroll das mensagens_

No meu caso, pelo que percebi, parece de fato que não consegue dar um scroll  e as mensagens simplesmente não aparecem na tela, porem vai pro destinatário e grava no banco certinho.

Não tive tempo de testar ainda, porem vou tentar ir por 2 vias. 

1 - Tendo em vista que nem todo mundo reclama deste problema na ver 1.9, pode ser algo relacionado com alguma lib que o S.O já contenha, que o Vue ou outro recurso do Front use. Talvez para não bater muito cabeça, valha a pena mudar de versão do S.O para testar. Aqui, eu estou testando no Ubuntu 22.04.2 LTS.
2 - Tentar utiliza a versão 1.6 do izing.

Se tiver algum progresso, compartilhe com a galera ai ... 

Grande abraço 

Otavio
