### ISSUE TITLE
É possível ter mais de uma conexão de WhatsZap na mesma empresa?

### ISSUE THREAD

**Issue by weltinhovzt** [ldurans/izing.open.io#130]
Não conseguir localizar como faz para adicionar mais de uma conta de WhatsZap, seria apenas criando uma nova empresa?

**Comment by fernandesrobert** [comment]
Sim é possível. No processo de instalação o izing pede 3 dominios.

**Comment by damianramirez** [comment]
Olá. Onde encontro essa página de administração? Só tenho uma página (de onde cadastro usuários e canais) mas ela não me deixa criar mais de um canal no WhatsApp. Como faço para adicionar mais um whatsapp?
![Captura de Pantalla 2023-05-08 a la(s) 16 26 20](https://user-images.githubusercontent.com/4790536/236914742-71366e2a-b140-4ab1-a2bb-e3189375eb5a.png)

**Comment by titioneamorim** [comment]
Também quero saber como gerenciamos isso, aguardo apoio.

**Comment by codsec** [comment]
Encontrou?

> Olá. Onde encontro essa página de administração? Só tenho uma página (de onde cadastro usuários e canais) mas ela não me deixa criar mais de um canal no WhatsApp. Como faço para adicionar mais um whatsapp? ![Captura de Pantalla 2023-05-08 a la(s) 16 26 20](https://user-images.githubusercontent.com/4790536/236914742-71366e2a-b140-4ab1-a2bb-e3189375eb5a.png)



> Olá, também quero saber como gerenciamos isso, aguardo apoio.

**Comment by KatiaSishost** [comment]
same here
