### ISSUE TITLE
Erro ao deletar mensagens, me ajudem por favor!!

### ISSUE THREAD

**Issue by VictorDelfino** [ldurans/izing.open.io#131]
quando tento deletar a mensagem que foi enviada recentemente, ele da esse erro no console
![image](https://user-images.githubusercontent.com/39544722/236842600-4ae670bc-8bfe-427f-9ae0-74d459c29c48.png)
e esse no terminal do pm2
![image](https://user-images.githubusercontent.com/39544722/236842966-4bad668e-1544-4b8d-9aeb-bfab959a4830.png)

**Comment by fernandesrobert** [comment]
verifique sua versão do wweb.js dentro do arquivo package.json na sua pasta de backend.

a versão mais recente é a 1.19.5

para atualizar faça: npm i whatsapp-web.js@^1.19.5
em seguida: npm run build

e reinicie o projeto backend, sendo por debug ou usando o pm2.

**Comment by VictorDelfino** [comment]
@fernandesrobert
