### ISSUE TITLE
Erro ao deletar mensagens, me ajudem por favor!!

### ISSUE THREAD

**Issue by VictorDelfino** [ldurans/izing.open.io#133]
Pessoal, me ajudem por favor, no meu terminal quando vou deletar uma mensagem, da esse erro aqui 
![image](https://github.com/ldurans/izing.open.io/assets/39544722/6f5eda7c-2381-46c2-9b6f-1dc71d85cf17)

 e no console do navegador da esse erro aqui  
![image](https://github.com/ldurans/izing.open.io/assets/39544722/e8de0467-ca04-4df3-8eb6-5ebc98709eae)

será que teria alguma solução desse caso?
ja atualizei a versão do wweb, e nada.

**Comment by titioneamorim** [comment]
Olá, como deleta mensagem?
