### ISSUE TITLE
Dificuldade em Conexão com o WhatsaApp

### ISSUE THREAD

**Issue by juniorcostin** [ldurans/izing.open.io#149]
Bom dia pessoal, 

Estou enfrentando uma dificuldade em me conectar com o whatsapp após realizar a configuração inicial.
Toda vez que eu tento gerar um novo QRCode, escaneio ele com meu Celular, sem nenhum problema, porém na interface nada acontece.
Aqui ele é o Google Chrome (MacOS)
![wats web](https://github.com/ldurans/izing.open.io/assets/32625506/428f2a1d-7caf-4430-881e-95c3e82ad57d)

Pela interface web o canal fica exatamente do mesmo jeito.
<img width="1217" alt="Captura de Tela 2023-08-29 às 09 29 05" src="https://github.com/ldurans/izing.open.io/assets/32625506/00dae062-eedf-44cb-b99e-fd0382ff28e7">

Logo após escanear o QRCode minhas logs ficam assim:
<img width="675" alt="Captura de Tela 2023-08-29 às 09 31 23" src="https://github.com/ldurans/izing.open.io/assets/32625506/ebd015cd-bd98-4289-a284-a092efda2fd4">
A principio parece estar buscando novas mensagens, correto?

Vi também em alguns comentários em outra Issue, para limpar o banco após o Migrate, porém não entendi bem como fazer
<img width="1680" alt="Captura de Tela 2023-08-29 às 09 33 31" src="https://github.com/ldurans/izing.open.io/assets/32625506/a24a43e7-3fa1-4c42-9899-e6a33b11bd95">

Na tentativa de ajustar eu atualizei a Lib do whatsapp-web.js para a ultima release: 1.22.1 no Package.JSON porém sem nenhuma mudança.

Alguém consegue me dar uma mão?

**Comment by tecinfotecnologia** [comment]
> Boa tarde amigo, também estava com o mesmo problema, fiquei a manhã inteira quebrando a cabeça. Parece problema na lib do whatsapp-js mesmo... Pois algumas outras aplicações caíram. Atualizei no package.JSON do backend a versão para **1.22.2-alpha.0** e resolvo meu problema, espero que ajude!

Boa tarde!
Estava com a mesma falha, segui sua orientação e resolveu meu problema.. Obrigado..

**Comment by render4us** [comment]
Como faço para atualizar o pupeteer? e fazer funcionar o whatsapp? aqui não aparecer o QR CODE

**Comment by doniani** [comment]
Olá Pessoal como faço para atualizar a Lib do whatsapp-web.js para a ultima release: 1.22.1 no Package.JSON? Obrigado!

**Comment by ldurans** [comment]
Atualizem para a versão 2.0, já está com a atualização da lib.
