### ISSUE TITLE
Melhoria: uso do mysql

### ISSUE THREAD

**Issue by igorssena** [ldurans/izing.open.io#151]
Poderia implementar o uso do mysql, ficaria mais familiar para o dev, postgressql é bem mais complicado

**Comment by Elielvitor45** [comment]
Olá igorssena, atualmente eu e um outro amigo estamos fazendo essa implementação, vai demorar um pouco ainda para o projeto estar terminado pois somos iniciantes rs.

**Comment by ldurans** [comment]
Obrigado pela sugestão, mas isso não será possível.
