### ISSUE TITLE
Whatsapp não gera o QR Code

### ISSUE THREAD

**Issue by render4us** [ldurans/izing.open.io#153]
Feito todas as atualizações incluindo a alteração da versão do whatsapp-web.js continuo sem conseguir ver o qr code, alguem passou por isso recentemente? Ps esse projeto foi abandonado? Se sim existem outros?

**Comment by KatiaSishost** [comment]
Hola vecino, actualice la versión de whatsappweb.js version y si, el proyecto parece abandonado, no encontré uno que continúe este. Si encuentra avise

Saludos desde Argentina

**Comment by sirquiroz** [comment]
Si encuentran otro lo comparten, aqui adjunto de otro compa https://github.com/codigoencasa/bot-whatsapp

**Comment by filipebsantos** [comment]
> Feito todas as atualizações incluindo a alteração da versão do whatsapp-web.js continuo sem conseguir ver o qr code, alguem passou por isso recentemente? Ps esse projeto foi abandonado? Se sim existem outros?

Também, atualizei para [1.22.2-alpha.0](https://github.com/pedroslopez/whatsapp-web.js/commit/b671b0c708f0bc6187ccec078a0f3e9c08db4bce) mas não tive resultado positivo, venho a vários dias quebrando cabeça com isso...

**Comment by alian87** [comment]
> Feito todas as atualizações incluindo a alteração da versão do whatsapp-web.js continuo sem conseguir ver o qr code, alguem passou por isso recentemente? Ps esse projeto foi abandonado? Se sim existem outros?

UPDATE WWEBJS 1.22.2-alpha.0 
backend\node_modules\whatsapp-web.js\src\Client.js

alterar linha 175 de: 
const INTRO_IMG_SELECTOR = '[data-icon=\'chat\']';

para: 
const INTRO_IMG_SELECTOR = 'div[role=\'textbox\']';

**Comment by ldurans** [comment]
Versão 2.0 já com a atualização da lib, funcionando como esperado.
