### ISSUE TITLE
Checkmessages em wbot.ts

### ISSUE THREAD

**Issue by joweste** [ldurans/izing.open.io#162]
Bom dia, porque o loop de checkmessages com setInterval no arquivo wbot.ts foi retirado?
Isso nao vai retardar o envio/recebimento de mensagens?

**Comment by ldurans** [comment]
Redesenhamos boa parte do núcleo da aplicação, melhorando a manutenabilidade. A retirada visa simplificar e evitar travamentos por longo tempo de uso.
