### ISSUE TITLE
Canais de WhatsApp não conecta

### ISSUE THREAD

**Issue by PauloBettin** [ldurans/izing.open.io#164]
Aparece o QR Code mas ao scanear da um erro. "Não foi possível conectar o aparelho, tente novamente mais tarde."

Entrando e saindo da tela de canais várias vezes, e também excluindo os canais e criando novamente enfim conseguir conectar.

**Comment by ldurans** [comment]
Quando isso oorrer, clique em gerar novo qr code e aguarde um momento, até que novo qr code apareca. 
Para os próximos reportes, tente incluir logs do back e do browser.
