### ISSUE TITLE
Mensagem do Bot fica na fila e não sai.

### ISSUE THREAD

**Issue by PauloBettin** [ldurans/izing.open.io#165]
A mensagem do Bot aparece no chat para o cliente porem ela fica com o icone do relógio e não sai, estou usando a ultima versão do izing e dois números de whatsapp configurados, o contato é recebido e o atendimento iniciado certinho, da pra conversa com contato normal, apenas a mensagem do bot fica aguardando e nunca vai.

**Comment by mrlonmra** [comment]
Conseguiu resolver? E onde você viu o erro no backend? Qual o caminho do log? Ou foi algum comando no terminal?

**Comment by mrlonmra** [comment]
![image](https://github.com/ldurans/izing.open.io/assets/26064875/7f08f486-9e19-4a0e-af59-7e4331a934c1)

**Comment by gcanapa** [comment]
Conseguiram resolver ? estou com o mesmo problema

**Comment by thigranpeio** [comment]
mesmo problema aqui

**Comment by ororodev** [comment]
Alguma novidade ?
estou exatamente com o mesmo problema... :(

**Comment by PauloBettin** [comment]
Não pessoal, infelizmente não consegui resolver voltei para a versão antiga do izing.

**Comment by mrlonmra** [comment]
Também não resolvi pessoal. Infelizmente.

**Comment by jrwanhouse** [comment]
O projeto e bacana, mais e triste , ver um retrocesso desse, visual ok , mais por causa disso o básico parou de funcionar, bem so atualizei pra testar essa verão ontem, hehehe , ate agora nada de novo na tentativa de resolver o problema e apesar de estar com uma nova cara e estrutura de bibliotecas em outros lugares, que na minha minha opinião so tornou uma forma mais difícil para a comunidade acompanhar e colaborar na depuração do bug e tentar ajudar na  resolução de qualquer problema, na boa e foda , gostaria de saber se a preocupação de mudar o licenciamento ou aparência e maior que a sua  funcionalidade, gera um pouco de descrédito e mostra que investir tempo na colaboração com o projeto não resulta no crescimento do mesmo, pois como dar apoio se so existe participação dos pais da criança de ano em ano, e meio que compre e use a versão oficial, pois a versão commuty e so um rascunho. Não estou querendo tirar o mérito ou depreciar o trabalho exposto,   alguém criar algo do zero e colocar para outros contribuirem no código seja para melhoria / uso próprio / colaboração , e maravilhoso e que merece reconhecimento, mas olhando pela óptica do sucesso e notório que projetos sólidos tem poucos forks, então decida github não serve pra criar fama ao meu ver serve para criar soluções viáveis e de colaboração  entre desenvolvedores. Desculpa ai o desabafo galera.

**Comment by ldurans** [comment]
https://github.com/ldurans/izing.open.io/releases/tag/v2.0.1

Resolvido
