### ISSUE TITLE
Problema com Websocket e conexão com o backend

### ISSUE THREAD

**Issue by ronaldovj** [ldurans/izing.open.io#166]
Olá, estou com um problema com a instalação do Izing, mesmo após fazer todos os passo da instalação, ao finalizar estou com um problema de conexão com o banco de dados. No console aparece problema com o websocket. Alguém conseguiu resolver esse erro já?

**Comment by smkbarbosa** [comment]
checa aqui https://github.com/ldurans/izing.open.io/issues/148

**Comment by jackperissute** [comment]
Olá.
Não qual processo está seguindo mas tente liberar a porta 8080 para o socket.io, para mim resolveu o problema de alertas de erro de conexão.

**Comment by ronaldovj** [comment]
> checa aqui #148

tentei e não funcionou

**Comment by ronaldovj** [comment]
> Olá. Não qual processo está seguindo mas tente liberar a porta 8080 para o socket.io, para mim resolveu o problema de alertas de erro de conexão.

Sem sucesso
