### ISSUE TITLE
Problema ao receber imagens na versão 2.0.1

### ISSUE THREAD

**Issue by PauloBettin** [ldurans/izing.open.io#168]
Primeiramente obrigado ao desenvolvedor que corrigiu meu ultimo post sobre um bug, das mensagens do chatbot não saindo.

Porém após o update pra versão 2.0.1 toda vez que recebo um áudio ou uma imagem o campo fica em negrito, não consigo exibir a mesma.

Tanto o arquivo de audio como a imagem chegam no diretório public do backend certinho, só a exibição no chat do programa que não funciona.

Alguém mais com o mesmo problema?

![Erro Imagem - Izing](https://github.com/ldurans/izing.open.io/assets/54962230/8d43b243-3e3f-4b6f-b59e-e4acb02e095f)

Perdão pessoal problema resolvido! era meu arquivo .env tinha uma variável errada.

**Comment by jvkabum** [comment]
qual estava?
