### ISSUE TITLE
Transferência de fila por inatividade não está funcionando

### ISSUE THREAD

**Issue by ronaldovj** [ldurans/izing.open.io#174]
Configurei o fluxo de atendimento  para mudar a fila do ticket quando o usuário não responde as mensagem do chatbot dentro de 30 minutos, porém não está funcionando. A variável notResponseMessage.time está correta no banco de dados.

**Comment by MtheusR** [comment]
Poise, to com esse problema também

**Comment by ronaldovj** [comment]
Consegui resolver excluindo o fluxo de atendimento e criando outro. Mas tive que excluir pelo banco de dados.

**Comment by MtheusR** [comment]
Valeu mano, dei um delete e funcionou. Acredito que a lógica é que quando há uma fila, não seria necessário filtrar sem filas. Abraços!
