### ISSUE TITLE
PM2

### ISSUE THREAD

**Issue by Monteiroemelo** [ldurans/izing.open.io#176]
Estou instalando o FRONTEND com PM2, porém não consigo dar o start com PM2.

1. npm install | ok
2. npm install -y pm2 -g | ok
3. npx quasar build -P -m pwa | ok
4. Comando do PM2 para iniciar?

**Comment by jrwanhouse** [comment]
Cria um arquivo server.js na raiz do frontend com o conteudo abaixo

// simple express server to run frontend production build;
const express = require('express')
const path = require('path')
const app = express()
app.use(express.static(path.join(__dirname, 'dist/pwa')))
app.get('/*', function (req, res) {
  res.sendFile(path.join(__dirname, 'dist/pwa', 'index.html'))
})
app.listen(3333)

build : quasar build -P -m pwa
run  : pm2 start server.js --name frontend

Bem foi a solução aqui para mim.

**Comment by Monteiroemelo** [comment]
Funcionou certinho. Obrigado!
