### ISSUE TITLE
Conexão cai

### ISSUE THREAD

**Issue by Monteiroemelo** [ldurans/izing.open.io#181]
O meu só funciona 1 dia, no outro a conexão cai e não volta mais. Excluo a conexão e faço outra, mais tem muita dificuldade de voltar, muitas vezes tem que fazer nova instalação.

**Comment by jrwanhouse** [comment]
Atualiza node para >18  , atualiza todos arquivos para versao atual
Roda npm install
Roda um npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

Com certeza seus problemas iram acabar.
