### ISSUE TITLE
Consumo de memória e processador

### ISSUE THREAD

**Issue by Monteiroemelo** [ldurans/izing.open.io#182]
Consumo de memória e processador é extremamente alto de um dia para o outro.

**Comment by jrwanhouse** [comment]
Detalhe , qual a plataforma , (distro/versão node/processador/memória) ? Pra eu tentar entender o que ocorre.. Se possível , quais os processos que rodam nessa instalação. Fica muito vago sem detalhar o problema e a plataforma.

**Comment by Monteiroemelo** [comment]
Já removi toda a VPS e contratei outra melhor.
