### ISSUE TITLE
Falta da pasta dist no github.

### ISSUE THREAD

**Issue by brunogmenezes** [ldurans/izing.open.io#186]
Olá, fiz a instalação conforme indicação do video, mas nao existe a pasta /frontend/dist 
Para onde aponto a pagina inicial que foi em /frontend/src, o index mostra apenas:
Congratulations, the site is created successfully!
This is the default index.html, this page is automatically generated by the system
The index.html of this page is in the site root directory
You can modify, delete or overwrite this page

**Comment by cleitonme** [comment]
tem que compilar codigo para aparecer essas pastas

**Comment by jrwanhouse** [comment]
Tenta se aprofundar mais no desenvolvimento em plataforma utilizando node, antes de tentar utilizar o código, ira evitar muitos problemas.
