### ISSUE TITLE
  opensslErrorStack: [ 'error:0308010C:digital envelope routines::unsupported' ]

### ISSUE THREAD

**Issue by danielton26** [ldurans/izing.open.io#200]
Bom dia Alguem poderia ajudar com esse erro 

![erro front](https://github.com/ldurans/izing.open.io/assets/22275932/3a69d244-dc54-4cec-837f-a3b8cbcbc23e)

**Comment by XNINGUEMX** [comment]
#143 olha aqui

**Comment by danielton26** [comment]
Obrigado
