### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by clubeplus** [ldurans/izing.open.io#54]
I can't login after installation

https://atendimento.clubeplus.com.br

**Comment by rcalbo** [comment]
Não esta encontrando o seu backend.

![image](https://user-images.githubusercontent.com/47294683/202248234-259f6bb9-578e-41a7-92a8-e98b396b7b2c.png)

**Comment by clubeplus** [comment]
O que eu faço?

**Comment by clubeplus** [comment]
Tentei de tudo aqui, mais sem resultado

**Comment by ldurans** [comment]
Verifique a instalação e a configuração do nginx. Como demonstrado pelo @rcalbo, o front não está conseguindo realizar requisições para o backend.
