### ISSUE TITLE
Tela de atendimento não está realizando Refresh automático

### ISSUE THREAD

**Issue by patronotech** [ldurans/izing.open.io#58]
Para que as conversar atualizem em alguns testes (esta intermitente) é necessário teclar F5 para que as novas e atuais conversas sejam mostradas na tela de atendimento.

**Comment by marcosambrozio** [comment]
Percebo essa situação também...

**Comment by imaxtechsistemas** [comment]
sabe me dizer se ja foi corrigido ?

**Comment by paulinhovba** [comment]
Bom dia. Ainda não foi corrigido não. Obrigado.

Em ter, 27 de dez de 2022 02:50, imaxtechsistemas ***@***.***>
escreveu:
