### ISSUE TITLE
Ajuste para exibir arquivos e ouvir gravação de audio

### ISSUE THREAD

**Issue by CarlosWemerson** [ldurans/izing.open.io#62]
Não da para ouvir as gravaçoes de audios, nao exibi videos, fotos e documentos

**Comment by ldurans** [comment]
Mostre mais detalhes para que possamos ajudar. Verifique sua instalação, permissões de pasta, se está utilizando https... Poste logs do browser, logs do backend...

**Comment by paulinhovba** [comment]
Estou com o mesmo problema... a última versão não permite visualizar arquivos de áudio e vídeo na tela de atendimento e não está enviando vídeos nas respostas do chatbot. Instalação verificada, permissões de pastas corretas e uso  de HTTPS corretamente.
