### ISSUE TITLE
erro npx sequelize db:migrate

### ISSUE THREAD

**Issue by whamulti** [ldurans/izing.open.io#64]
Olá Duran, já conseguiu identificar porque em momentos não conseguimos fazer o npx sequelize db:migrate, retorna no final o erro

ERROR: column "queue" of relation "Tickets" already exists

![migrate](https://user-images.githubusercontent.com/116593038/203307698-c81be893-f469-4f03-9ea9-b8aa400975a9.png)

**Comment by carloslencargorges** [comment]
estou com o mesmo erro

**Comment by ninjoan** [comment]
i have the same error create a new database an run again. try to use a database with a username different from the database name
sample

database: db1
database user: userdb1

**Comment by ldurans** [comment]
Acabei de fazer um commit para tentar evitar esse erro. Façam um pull e testem, por favor.
