### ISSUE TITLE
erro na hora do login This request has been blocked; the content must be served over HTTPS

### ISSUE THREAD

**Issue by carloslencargorges** [ldurans/izing.open.io#67]
quando tento realizar o login encontro um erro This request has been blocked; the content must be served over HTTPS.

![image](https://user-images.githubusercontent.com/98112671/203454465-ad076276-bed5-432f-b766-187f57f82fa4.png)

**Comment by ninjoan** [comment]
check the .env configuration if the BACKEND is set to https
