### ISSUE TITLE
Problems after fresh install

### ISSUE THREAD

**Issue by ninjoan** [ldurans/izing.open.io#69]
![Desktop-screenshot (10)](https://user-images.githubusercontent.com/14807878/204116682-b5ca4600-167e-4556-a7ec-5a6551bafb87.png)
Hello, thank you for this interesting project.
I have some inconveniences when synchronizing with WhatsApp the QR code is not generated and I see an error in the console. Does anyone know how to fix this.

I am running on Ubuntu 20.04

---------
Olá, obrigado por este interessante projeto.
Eu tenho alguns problemas ao sincronizar com o WhatsApp o código QR não é gerado e vejo um erro no console. Alguém sabe como consertar isto.

Estou correndo no Ubuntu 20.04

**Comment by ninpartners** [comment]
now i have problems with CORS

**Comment by ldurans** [comment]
Verifique os parâmetros de instalação. O socket não está conseguindo conectar ao backend.
