### ISSUE TITLE
Erro na hora de gerar o qrcode do whatsapp

### ISSUE THREAD

**Issue by carloslencargorges** [ldurans/izing.open.io#71]
Estou com problema na hora de gerar o qrcode do whatsapp, fica aternamente gerando e nada acontece. Analizando o banco de dados da pra ver que realmente não é gerado

**Comment by ldurans** [comment]
Envei os logs do back e front.

**Comment by Horgun** [comment]
Provavelmente relacionado ao puppeteer, passei por esse problema ao instalar a versão docker

**Comment by pablowilliam** [comment]
Alguém conseguiu corrigir isto que poderia me ajudar?

**Comment by pablowilliam** [comment]
O meu gera o QR Code porém não deixa conectar e manda tentar novamente mais tarde

**Comment by dravagnolli** [comment]
Tambem estou com o mesmo problema. Gera o Qr code mas não conecta

**Comment by dravagnolli** [comment]
Testa Essa solução

cd izing/backend (pasta onde ta instalado o izing) 
 
npm r whatsapp-web.js 
 
npm i whatsapp-web.js 
 
pm2 start 0

**Comment by ralphhayashi** [comment]
Deu Certo, muito obrigado, Deus te abençoe

**Comment by DaviMAC02** [comment]
Solução funcionou por aqui também, obrigado!
