### ISSUE TITLE
Docker do backend Restartando...

### ISSUE THREAD

**Issue by iranbk** [ldurans/izing.open.io#83]
ola, estou rodando localmente para testar, usei o tutorial do inicio ali rodei o primeiro comando para criar os container apos fui rodar o segundo e ja deu erro
ai fui ver o container do backend esta restanrd e no log aparece a seguinte mensagem
command not found: sequelize... e fica nesse loop, ja removi todos os container e tentei novamente segue o erro, ate abre no navegador a pagina do izing porem nao faz login.

**Comment by Horgun** [comment]
Acabei de arrumar isso no meu
![image](https://user-images.githubusercontent.com/14986135/207416408-1b5b0981-7bf5-451f-b441-06b2d2dba456.png)
Diff do Dockerfile (só alterar a linha vermelha pela verde no seu)

![image](https://user-images.githubusercontent.com/14986135/207416600-a9c74758-f091-4e31-9e0d-43d312152003.png)
Diff do backend/Dockerfile (só alterar a linha vermelha pela verde no seu)

![image](https://user-images.githubusercontent.com/14986135/207416751-fd7fc1f6-afc0-4a47-897c-5dd0de726709.png)
no backend/.env coloca assim

**Comment by iranbk** [comment]
> Acabei de arrumar isso no meu ![image](https://user-images.githubusercontent.com/14986135/207416408-1b5b0981-7bf5-451f-b441-06b2d2dba456.png) Diff do Dockerfile (só alterar a linha vermelha pela verde no seu)
> 
> ![image](https://user-images.githubusercontent.com/14986135/207416600-a9c74758-f091-4e31-9e0d-43d312152003.png) Diff do backend/Dockerfile (só alterar a linha vermelha pela verde no seu)
> 
> ![image](https://user-images.githubusercontent.com/14986135/207416751-fd7fc1f6-afc0-4a47-897c-5dd0de726709.png) no backend/.env coloca assim
> 
> Agora to tentando entender como cria conexao (canal), pq nao tem um botao pra isso

Ola obrigado pela resposta, desculpa, e que comecei agora mexer com docker, qual diretório fica esse arquivo mesmo ? obrigado

**Comment by iranbk** [comment]
> izing.io/Dockerfile izing.io/backend/Dockerfile izing.io/backend/.env
> 
> ah, tb alterei a porta pra 3000 no arquivo: izing.io/frontend/.env

novamente obrigado amigo, fiz as alteracoes, rodei novamente o comando
porem ainda continua restart o container do backend nos logs agora aparece esse erro

9 2022/12/13 23:48:09 Problem with dial: dial tcp: missing address. Sleeping 1s
2022-12-13 20:48:10 2022/12/13 23:48:10 Problem with dial: dial tcp: missing address. Sleeping 1s
2022-12-13 20:48:11 2022/12/13 23:48:11 Problem with dial: dial tcp: missing address. Sleeping 1s
2022-12-13 20:48:12 2022/12/13 23:48:12 Problem with dial: dial tcp: missing address. Sleeping 1s
2022-12-13 20:48:13 2022/12/13 23:48:13 Timeout after 10s waiting on dependencies to become available: [tcp:://host.docker.internal:5432]

**Comment by Horgun** [comment]
Depois de alterar vc rodou docker-compose up --build na pasta raiz izing.io?
No meu teve um momento que nao tava dando certo pq eu tava tentando executar a partir da pasta izing.io/backend

Depois de fazer as alterações vai até a pasta izing.io e roda `docker-compose up --build`
Roda sem o -d mesmo pra vc ja ir vendo as mensagens que aparecem

**Comment by iranbk** [comment]
isso jovem rodei o comando dentro do izing
docker compose -f "docker-compose.yml" up -d --build
ai ele cria os contianers
dps quando vou rodar o 
docker compose exec -it izing-backend  bash -c 'npx sequelize db:seed:all'    
ja da erro ai quando vou ver o contianer fica reiniciando

**Comment by rafamadeira** [comment]
![image](https://user-images.githubusercontent.com/84319840/207580876-066648c6-a8ab-4a9f-a7ba-e8ca5e597403.png)

Infelizmente aqui tbm, estou com o mesmo erro, ja fiz as sugestões acima, mas continua

**Comment by Horgun** [comment]
> [tcp:://host.docker.internal:5432]

confere se ta com esse ":" a mais no arquivo, se estiver ta errado

**Comment by Horgun** [comment]
> ![image](https://user-images.githubusercontent.com/84319840/207580876-066648c6-a8ab-4a9f-a7ba-e8ca5e597403.png)
> 
> Infelizmente aqui tbm, estou com o mesmo erro, ja fiz as sugestões acima, mas continua

ahhh, consegui replicar aqui, é que eu ja tinha tentando outras coisas, por isso o meu deu certo.
Depois que eu resetei tudo tb voltou a apresentar esse erro.
Aparentemente oq acontece é que no Dockerfile quando ele roda o RUN npm install e RUN npm run build nao ta acontecendo nada. As pastas não são criadas.
Vou ver se consigo arrumar.

**Comment by iranbk** [comment]
entao ja ne vou tentar heheheh ,tranquilo amigo se descobrir e poder avisar obrigado

**Comment by matheusmaiberg** [comment]
Tentem o seguinte

No arquivo Dockerfile do backend que fica em /izing/backend/Dockerfile

Adicionem a linha na linha 5
`RUN npm install typescript -g
` 

E alterem na linha 27 para 
`RUN npm install --force
`

Iniciem isso em uma nova instalacao.

Acredito que é um erro do sequelize que não está encontrando os pacotes, isso deve resolver.

**Comment by iranbk** [comment]
ola amigo, efetuei os procedimentos assim porem ainda continua restardando o container e segue o log de erro

npx: installed 22 in 1.836s
2022-12-15 09:30:22 command not found: sequelize
2022-12-15 09:30:36 2022/12/15 12:30:36 Waiting for: tcp://host.docker.internal:5432
2022-12-15 09:30:36 2022/12/15 12:30:36 Connected to tcp://host.docker.internal:5432
npx: installed 22 in 1.975s
2022-12-15 09:30:38 command not found: sequelize
2022-12-15 09:31:05 2022/12/15 12:31:05 Waiting for: tcp://host.docker.internal:5432
2022-12-15 09:31:05 2022/12/15 12:31:05 Connected to tcp://host.docker.internal:5432
npx: installed 22 in 2.398s
2022-12-15 09:31:07 command not found: sequelize

**Comment by Horgun** [comment]
Eu consegui fazer funcionar mas acredito que nao seja a forma ideal de se resolver, estou pesquisando ainda.
Pelo jeito é devido ao volume, ele não é montado na build da imagem do docker. Quando termina de buildar a imagem o volume que está definido como a pasta do backend sobrescreve a pasta dentro do container, apagando as pastas node_modules e dist que tinham sido geradas.
Mas se quiserem:
Alterar o arquivo backend/Dockerfile
```Dockerfile
FROM node:14 as build-deps

RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN apt-get update \
  && apt-get install -y wget gnupg \
  && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
  --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.1/dumb-init_1.2.1_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

ENV NODE_ENV=production
ENV CHROME_BIN=google-chrome-stable

COPY ./start_production /start_production
RUN sed -i 's/\r$//g' /start_production
RUN chmod +x /start_production

ENTRYPOINT ["dumb-init", "--"]
CMD dockerize -wait tcp://${POSTGRES_HOST}:5432 \
  && [ ! -d "dist" ] && echo "buildando a primeira vez" && npm install && npm run build && iniciou="sim" || echo "build ja rodou a primeira vez" \
  && npx sequelize db:migrate \
  && node dist/server.js
```
O que eu fiz foi mandar rodar o npm install e npm run build ao iniciar o container do izing-backend, antes de rodar os outros comandos que ja estavam definidos.

Agora só testar e ver se isso vai ter algum efeito colateral.

**Comment by iranbk** [comment]
> Eu consegui fazer funcionar mas acredito que nao seja a forma ideal de se resolver, estou pesquisando ainda. Pelo jeito é devido ao volume, ele não é montado na build da imagem do docker. Quando termina de buildar a imagem o volume que está definido como a pasta do backend sobrescreve a pasta dentro do container, apagando as pastas node_modules e dist que tinham sido geradas. Mas se quiserem: Alterar o arquivo backend/Dockerfile
> 
> ```dockerfile
> FROM node:14 as build-deps
> 
> RUN apt-get update && apt-get install -y wget
> 
> ENV DOCKERIZE_VERSION v0.6.1
> RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
>   && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
>   && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
> 
> RUN apt-get update \
>   && apt-get install -y wget gnupg \
>   && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
>   && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
>   && apt-get update \
>   && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
>   --no-install-recommends \
>   && rm -rf /var/lib/apt/lists/*
> 
> ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.1/dumb-init_1.2.1_amd64 /usr/local/bin/dumb-init
> RUN chmod +x /usr/local/bin/dumb-init
> 
> ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
> 
> WORKDIR /usr/src/app
> COPY package*.json ./
> RUN npm install
> 
> COPY . .
> RUN npm run build
> 
> ENV NODE_ENV=production
> ENV CHROME_BIN=google-chrome-stable
> 
> COPY ./start_production /start_production
> RUN sed -i 's/\r$//g' /start_production
> RUN chmod +x /start_production
> 
> ENTRYPOINT ["dumb-init", "--"]
> CMD dockerize -wait tcp://${POSTGRES_HOST}:5432 \
>   && [ ! -d "dist" ] && echo "buildando a primeira vez" && npm install && npm run build && iniciou="sim" || echo "build ja rodou a primeira vez" \
>   && npx sequelize db:migrate \
>   && node dist/server.js
> ```
> 
> O que eu fiz foi mandar rodar o npm install e npm run build ao iniciar o container do izing-backend, antes de rodar os outros comandos que ja estavam definidos.
> 
> Agora só testar e ver se isso vai ter algum efeito colateral.
> 
> Também tive que alterar o arquivo backend/src/libs/wbot.ts devido a um outro erro. Procura onde estiver puppeteer e altera a linha `` args: [`--user-agent=${DefaultOptions.userAgent}\`] `` para:
> 
> ```ts
> args: [`--user-agent=${DefaultOptions.userAgent}`, '--no-sandbox']
> ```

mestreeee funicionou pelo menos nao reinicou heheh, porem tentei fazer login ai nao deu
fui rodar esse outro comando
docker compose exec -it izing-backend  bash -c 'npx sequelize db:seed:all'    

ai ja retornou erro 
 docker compose exec -it izing-backend  bash -c 'npx sequelize db:seed:all'
time="2022-12-15T15:09:06-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T15:09:07-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T15:09:07-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T15:09:07-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T15:09:07-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T15:09:07-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T15:09:07-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
npx: installed 22 in 10.859s
command not found: sequelize

**Comment by matheusmaiberg** [comment]
Opa, pode ser um pouco tarde mas vou deixar pra quem precisar resolver quando ele não achar o sequelize

```
sudo npm install -g sequelize 
sudo npm i -g sequelize-cli
```

Isso vai fazer com que o sequelize seja instalado globalmente, mas eu percebi o erro do arquivo sendo apagado o que tem dentro do node_modules e dist, também não sei como resolver isso.

Mesmo que rode o sequelize ele traz o erro.

Ele acaba se resolvendo depois de um tempo quando reinicia container do postgres, realmente não entendo o que acontece.

**Comment by Natan738** [comment]
também estou com esse mesmo problema.
já fiz tudo mencionado acima, porém continua dando o erro.
![image](https://user-images.githubusercontent.com/119529533/211171732-130dca80-0380-4a31-86c0-6b37c1957267.png)

**Comment by andrerds** [comment]
Fala devs, seguindo os passos do mano @iranbk e do @matheusmaiberg  , conseguir subir sem ficar reiniciando o backend.
Porém vi que os postgress nao inicializa nem a pau. Ainda investigando que pode ser.
Para os próximos que virem esse post, sigam nessa ordem > https://github.com/ldurans/izing.open.io/issues/83#issuecomment-1353169866
depois > https://github.com/ldurans/izing.open.io/issues/83#issuecomment-1356670144

Porem no em vez de add sudo, no Dockerfile, eu adicionei 
abaixo de **RUN npm install**. 
 
RUN npm install
**RUN npm install -g sequelize**
**RUN npm i -g sequelize-cli**

Boa sorte para nois! Então, eu não manjo muito de docker, mas se conseguir deixar uma funcional, irei subir uma *PR*  ou add aqui, pois irá vai ajudar  outras pessoas noobs em docker com eu.

**Comment by danieltec2016** [comment]
Fala Pessoal, conseguir resolver esse problema no postgress ? valew

**Comment by danieltec2016** [comment]
Fala Pessoal, conseguiram resolver esse problema no postgress ? Abraço!

**Comment by andrerds** [comment]
Olá pessoal, larguei de mão, acabei de limpar a minha maquina local e VPS, e  infelizmente não consegui resolver o problema no Postgres, e nem rodar no docker corretamente depois de um serie de modificações.  Não tenho muito conhecimento e nem expertise em Docker,  mas creio que  os arquivos aqui presente na documentação não estão claros o suficiente para que possam ser executados corretamente. Enfim, não consigo ajudar em nada, eu  só tenho conhecimento básico em Docker. No entanto, acredito que algo esteja errado, pois vejam a quantidade de modificações que as pessoas estão tentando fazer para que funcione corretamente. Projeto fantástico mas documentação parece esta largado abandonado jogado as traças kkkk profundo.

**Comment by marllonsiqueira** [comment]
Ola pessoal, não sou programador, mas 2 dias batendo cabeça aqui e com ajuda do GPT segui essa sequência para instalação Docker

![image](https://github.com/ldurans/izing.open.io/assets/78931107/998c8c11-3c58-4ed2-9f31-0242167ca7d2)

Alterei a linha 14 e 15 do package


1- DOWNLOAD GIT, NODE, DOCKER
git clone https://github.com/ldurans/izing.io.git
docker run --name postgresql -e POSTGRES_USER=izing -e POSTGRES_PASSWORD=password -p 5432:5432 -v /data:/var/lib/postgresql/data3 -d postgres
docker run -e TZ="America/Sao_Paulo" --name redis-izing -p 6379:6379 -d --restart=always redis:latest redis-server --appendonly yes --requirepass "password"
docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 --restart=always --hostname rabbitmq -v /data:/var/lib/rabbitmq rabbitmq:3-management-alpine
cd izing/backend
npm install rimraf --save-dev
npm install --force
npm run build
npm run db:migrate
npm run db:seed
cd izing/frontend
npm i -g @quasar/cli
npm install
npx quasar build -P -m pwa
npx quasar dev
