### ISSUE TITLE
Erro ao executar o projeto

### ISSUE THREAD

**Issue by Feppeli** [ldurans/izing.open.io#86]
Instalei o docker o postgre e tudo mais, porém me gera varios erros ao executar os códigos no terminal :

PS C:\Users\dfsil\OneDrive\Área de Trabalho\projetoNovo\izing.io> docker compose -f "docker-compose.yml" up -d --build
time="2022-12-15T00:59:00-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T00:59:00-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T00:59:00-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T00:59:00-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T00:59:00-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T00:59:00-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
time="2022-12-15T00:59:00-03:00" level=warning msg="The \"HOME\" variable is not set. Defaulting to a blank string."
open C:\Users\dfsil\OneDrive\Área de Trabalho\projetoNovo\izing.io\backend\.env: O sistema não pode encontrar o arquivo especificado.

Como posso solucionar?

**Comment by iranbk** [comment]
bom dia amigo
voce esta executando dentro do backend
da um cd ..
e roda o comando dentro do \izing.io\
e marcha !

**Comment by andradevander** [comment]
No .env da raiz do projeto cria a Variavel HOME
Exemplo:
HOME=./envirnment

**Comment by matheusmaiberg** [comment]
Acredito que ele não alterou a example.env para .env, consegui replicar esse erro assim.

É só entrar na pasta frontend e tambem na backend e alterar os `example.env` para `.env` e alterar também o que tem dentro deles para seu ambiente.
