### ISSUE TITLE
F5 para Atualizar a página para mostrar novas mensagens

### ISSUE THREAD

**Issue by marcosambrozio** [ldurans/izing.open.io#93]
Ola, tinha a versão 1.6 e ao atualizar para a versão 1.9, as mensagens trocadas não são mostradas automaticamente, tanto as recebidas como as enviadas, somente após apertar F5 para Atualizar elas aparecem.

**Comment by andrerds** [comment]
Fala @marcosambrozio , blza , ainda esta com esse problema ?

**Comment by Jacs5** [comment]
olá, estou usando te teste e estou com esse erro, com resolver?

**Comment by JrZavaschi** [comment]
Olá,
- Confira a versão do websocket para frontend e backend, ambas devem ser a mesma.
- Confira o console do navegador, não podem existir erros de websocket sendo gerados.

**Comment by laschicasmagicas** [comment]
> 

Poderia explicar como fazer isso? Preciso de uma ajudinha para fazer isso funcionar ^^

**Comment by JrZavaschi** [comment]
> > 
> 
> Poderia explicar como fazer isso? Preciso de uma ajudinha para fazer isso funcionar ^^

em package.json na pasta /frontend e /backend, confere as versões do socket.io e socket.io-client, elas precisam ser as mesmas.
Se precisar atualizar, remove e instala novamente com npm r, npm i

**Comment by laschicasmagicas** [comment]
> 
acabei de verificar, e tanto o frontend como backend estão como " "socket.io-client": "^3.0.5"," 

Ouvi falar que eu deveria deletar os arquivos "package-lock.json" será que é isso?

**Comment by andrerds** [comment]
> > 
> 
> acabei de verificar, e tanto o frontend como backend estão como " "socket.io-client": "^3.0.5","
> 
> Ouvi falar que eu deveria deletar os arquivos "package-lock.json" será que é isso?

Opa, esse arquivo em teoria e para fixar a versão que esta no package.json.
Em alguns projetos, ao deletar esse arquivo, chega nem instala as dependências corretamente, digo por experiência. 
Ele ajuda a garantir que tudo funcione da mesma forma em diferentes computadores ou momentos. É importante incluir esse arquivo no controle de versão para que outras pessoas consigam reproduzir o ambiente de trabalho.

Assim, você pode tentar excluir e ver o resultado, especialmente no último caso, quando for necessário.

**Comment by andrerds** [comment]
> > > 
> > 
> > 
> > Poderia explicar como fazer isso? Preciso de uma ajudinha para fazer isso funcionar ^^
> 
> em package.json na pasta /frontend e /backend, confere as versões do socket.io e socket.io-client, elas precisam ser as mesmas. Se precisar atualizar, remove e instala novamente com npm r, npm i

Opa, saquei, mais creio que seja um bug no front, ainda não tive tempo de avaliar, quando fica navegando entre as paginas do nada volta a funcionar, como não conheço o Quasar + Vue, não sei se tem algo a ver com navegação ou ciclo de vida do component.

**Comment by andrerds** [comment]
> Olá,
> 
> * Confira a versão do websocket para frontend e backend, ambas devem ser a mesma.
> * Confira o console do navegador, não podem existir erros de websocket sendo gerados.

Conferido, sem erros, mas anteriormente, não esta na documentação ou não e validos para todos, fazer um ajuste no proxy reverse Ngnix para o socket io.  

location ^~ /socket.io/ 
{
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:3000/socket.io/;
}

**Comment by JrZavaschi** [comment]
Se as versões estão iguais, faça um outro teste:
em backend\src\libs\socket.ts
comenta a linha 74 `// next(new Error("authentication error"));`

**Comment by VictorDelfino** [comment]
Olá pessoa, Boa tarde
o meu esta dando esse probleminha aqui
WebSocket connection to 'wss://apii.apoioamestra.com.br/socket.io/?EIO=4&transport=websocket' failed: 
podem me ajudar? @andrerds @JrZavaschi

**Comment by NoNAT-Telecom** [comment]
Estou com esse mesmo problema 'wss://apii.testederede.com.br/socket.io/?EIO=4&transport=websocket', alguém já como ajudar?

As mensagem não carrega a não ser que dê refresh na pagina com F5.

**Comment by andrerds** [comment]
Opa, tem um video , vou procuar 

> Olá pessoal, Boa tarde o meu esta dando esse probleminha aqui WebSocket connection to 'wss://apii.apoioamestra.com.br/socket.io/?EIO=4&transport=websocket' failed: no console do navegador podem me ajudar? @andrerds @JrZavaschi

veja esse video, que e possível solução correta.
https://youtu.be/R-dOi2R1tkU?t=2092

**Comment by Luizhcrs** [comment]
Tenho o mesmo problema conseguiu resolver?

**Comment by andrerds** [comment]
> https://youtu.be/R-dOi2R1tkU?t=2092

com esse video aqui, https://youtu.be/R-dOi2R1tkU?t=2092 nao deu certo ?
se não deu não sei, pois a minha solução nao é muito correta.
